name: Update Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-suggestion-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Suggestion of the Day script
      run: python ./suggestionoftheday.py

    - name: Check logs for debugging
      run: |
        tail -n 50 ./suggestionoftheday.log || echo "No logs available"

    - name: Post failure message if script fails
      if: failure()
      run: |
        echo "Script failed. Please check the logs for details."

# name: Update README

# on:
#   schedule:
#     - cron: "0 17,5 * * *" # Runs every day at noon and midnight EST
#   workflow_dispatch:

# jobs:
#   update-readme:
#     runs-on: ubuntu-latest
#     env:
#       MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v2
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: "3.x"
#       - name: Debugging step (List directory)
#         run: ls -al
#       - name: Debugging step (Check secret length)
#         run: echo "Length of MY_SECRET_KEY is ${#MY_SECRET_KEY}"
#       - name: Debugging step (Check Python version)
#         run: python --version
#       - name: Debugging step (Check environment variables)
#         run: env
#       - name: Install dependencies
#         run: pip install -r requirements.txt
#       - name: Run Python script
#         run: python ./jokeofday.py
#       - name: Run AI Suggestion of the Day Python script
#         run: python ./suggestionoftheday.py
