name: Update README

on:
  schedule:
    - cron: '08 5 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Debugging step (List directory)
      run: ls -al
    - name: Debugging step (Check secret length)
      run: echo "Length of MY_SECRET_KEY is ${#MY_SECRET_KEY}"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Python script
      run: python ./jokeofday.py
